# number of all possible servo channels
all_servo_channels: 16

mqtt:
  host: localhost
  username: username
  password: password
  # assumes get, set, availability subtopics and default payloads e.g. 'online/offline' for .../availability
  # need to coincide with topics declared in the `configuration.yaml` for HA
  sensor_base_topic: living_room/vcnl4040
  cover_base_topic: living_room/blinds
  util_base_topic: living_room/blinds_util

servo_channels:
  # integer denotes the channel for the servo
  0:
    # Current status of the blind 0 is completely up, 1 is completely down. Required.
    status: 0.0
    # determines how the servo is operated
    servo_type: continuous_hacked
    # hacked servos that use degrees for a specified amount of time to achieve continuous rotation
    servo_details:
      stationary_degrees: 93
      open_time: 3
      close_time: 3
      open_degrees: 91
      close_degrees: 95
  1:
    status: 0.0
    servo_type: continuous_hacked
    servo_details:
      stationary_degrees: 93
      open_time: 3
      close_time: 3
      open_degrees: 91
      close_degrees: 95
  2:
    status: 0.0
    servo_type: continuous_hacked
    servo_details:
      stationary_degrees: 93
      open_time: 3
      close_time: 3
      open_degrees: 91
      close_degrees: 95
